import Paystack from 'paystack-api';
import retry from 'async-retry';
import { db } from '../config/db';
import { createUser, getUserByEmail, updateUser } from '../models/userModel';
import { PaymentPlan, TransactionStatus, Roles } from '@prisma/client';
import { getCountryByIp } from '../lib/getCountryByIp';
import { addMonths } from 'date-fns'; // Add this library for precise month addition

const paystack = Paystack(process.env.PAYSTACK_SECRET_KEY || '');

const PRICES: Record<PaymentPlan, { NGN: number; USD: number }> = {
  BASIC_ONETIME: { NGN: 200000, USD: 399 },
  LOCAL_MONTHLY: { NGN: 550000, USD: 899 },
  GLOBAL_MONTHLY: { NGN: 950000, USD: 1499 },
};

// Map PaymentPlan to Paystack plan codes (must be created in Paystack dashboard)
// These plan codes are generated by Paystack and linked to specific subscription plans.
// - BASIC_ONETIME: Empty as it’s a one-time payment, no subscription required.
// - LOCAL_MONTHLY: Plan code for the Local Monthly plan (NGN 5,500/month or USD $8.99/month).
// - GLOBAL_MONTHLY: Plan code for the Global Monthly plan (NGN 9,500/month or USD $14.99/month).
// Note: These codes must match the plans created in the Paystack dashboard under Subscriptions > Plans.
// Created on: June 04, 2025.
// const PAYSTACK_PLAN_CODES: Record<PaymentPlan, string> = {
//   BASIC_ONETIME: '', // Not needed for one-time payments
//   LOCAL_MONTHLY: 'PLN_0s54bpaqt1zoe3d', // Local Monthly plan code
//   GLOBAL_MONTHLY: 'PLN_g4vdb2pu9mdpwrk', // Global Monthly plan code
// };

const PAYSTACK_PLAN_CODES: Record<PaymentPlan, { NGN: string; USD: string }> = {
  BASIC_ONETIME: { NGN: '', USD: '' }, // Not needed for one-time payments
  LOCAL_MONTHLY: { NGN: 'PLN_0s54bpaqt1zoe3d', USD: 'PLN_uh2v4rnvyc6pw7h' },
  GLOBAL_MONTHLY: { NGN: 'PLN_g4vdb2pu9mdpwrk', USD: 'PLN_hgfa4dnb463jipw' },
};

export const initializeBasicOneTimePayment = async (
  email: string,
  firstname: string,
  lastname: string,
  schoolLocation: string,
  paymentPlan: PaymentPlan,
  ip: string
) => {
  const region = getCountryByIp(ip);
  const isUsdEnabled = process.env.ENABLE_USD === 'true';
  const currency = isUsdEnabled && region !== 'Nigeria' ? 'USD' : 'NGN';
  const amount = PRICES[paymentPlan][currency];
  const callbackUrl = `https://www.aligntrait.com/payment/callback`;

  let user = await getUserByEmail(email);
  if (!user) {
    user = await createUser({
      data: {
        firstname,
        lastname,
        email,
        password: '',
        emailVerified: new Date(),
        role: Roles.USER,
      },
    });
  }

  const reference = `one_${user.id}_${paymentPlan}_${Date.now()}`;
  await db.transaction.create({
    data: {
      userId: user.id,
      paymentPlan,
      amount: amount / 100,
      currency,
      reference,
      schoolLocation,
      status: TransactionStatus.PENDING,
    },
  });

  const paystackResponse = await retry(
    async () =>
      await paystack.transaction.initialize({
        email: user.email,
        amount,
        currency,
        reference,
        callback_url: callbackUrl,
        metadata: { userId: user.id, paymentPlan, schoolLocation },
        channels: ['card', 'bank_transfer'],
      }),
    { retries: 3, minTimeout: 1000, maxTimeout: 5000 }
  );

  return {
    ok: true,
    status: 200,
    message: 'Payment initialized',
    data: {
      authorization_url: paystackResponse.data.authorization_url,
      reference: paystackResponse.data.reference,
    },
  };
};

// Helper function to handle customer creation/fetching
async function getOrCreateCustomer(
  email: string,
  firstname: string,
  lastname: string
) {
  try {
    // First try to find existing customer
    const customers = await paystack.customer.list({ email });
    if (customers.data && customers.data.length > 0) {
      return customers.data[0];
    }

    // Create new customer if not found
    const newCustomer = await paystack.customer.create({
      email,
      first_name: firstname,
      last_name: lastname,
    });
    return newCustomer.data;
  } catch (error) {
    console.error('Error handling customer:', error);
    throw new Error('Failed to process customer');
  }
}

export const initializeMonthlySubscription = async (
  email: string,
  firstname: string,
  lastname: string,
  schoolLocation: string,
  paymentPlan: PaymentPlan,
  ip: string
) => {
  try {
    const region = getCountryByIp(ip);
    const isUsdEnabled = process.env.ENABLE_USD === 'true';
    const currency = isUsdEnabled && region !== 'Nigeria' ? 'USD' : 'NGN';
    const amount = PRICES[paymentPlan][currency]; // Select amount based on currency
    const callbackUrl = `https://www.aligntrait.com/payment/callback`; // Fixed template literal

    let user = await getUserByEmail(email);
    if (!user) {
      user = await createUser({
        data: {
          firstname,
          lastname,
          email,
          password: '',
          emailVerified: new Date(),
          role: Roles.USER,
        },
      });
    }

    const reference = `sub_${user.id}_${paymentPlan}_${Date.now()}`;

    await db.transaction.create({
      data: {
        userId: user.id,
        paymentPlan,
        amount: amount / 100, // Convert to units (kobo/cents to NGN/USD)
        currency,
        reference,
        schoolLocation,
        status: TransactionStatus.PENDING,
      },
    });

    // Get or create Paystack customer
    const customer = await retry(
      () => getOrCreateCustomer(user.email, user.firstname, user.lastname),
      { retries: 3 }
    );

    const paystackResponse = await retry(
      async () => {
        const params: any = {
          email: user.email,
          amount,
          currency, // Pass the selected currency
          reference,
          callback_url: callbackUrl,
          metadata: {
            userId: user.id,
            paymentPlan,
            auto_renew: true,
          },
          channels: ['card'],
        };

        // For monthly plans, include the plan code based on currency
        if (paymentPlan !== 'BASIC_ONETIME') {
          params.plan = PAYSTACK_PLAN_CODES[paymentPlan][currency];
        }

        return await paystack.transaction.initialize(params);
      },
      { retries: 3 }
    );

    return {
      ok: true,
      status: 200,
      message: 'Subscription payment initialized',
      data: {
        authorization_url: paystackResponse.data.authorization_url,
        reference: paystackResponse.data.reference,
      },
    };
  } catch (error: any) {
    console.error('Error initializing subscription:', error);
    return {
      ok: false,
      status: 500,
      message: 'Failed to initialize subscription',
      error: error.message,
    };
  }
};

export const verifySubscriptionPaymentService = async (
  reference: string,
  event: string
) => {
  try {
    const transaction = await db.transaction.findUnique({
      where: { reference },
    });
    if (!transaction) {
      return { ok: false, status: 404, message: 'Transaction not found' };
    }

    // Verify transaction first
    const verification = await paystack.transaction.verify({ reference });
    if (verification.data.status !== 'success') {
      console.error('Verification failed:', verification.data);
      return { ok: false, status: 400, message: 'Verification failed' };
    }

    const status =
      event === 'charge.success'
        ? TransactionStatus.SUCCESS
        : TransactionStatus.FAILED;

    await db.transaction.update({
      where: { reference },
      data: { status },
    });

    if (status !== TransactionStatus.SUCCESS) {
      return { ok: true, status: 200, message: 'Payment failed' };
    }

    const authorization = verification.data.authorization;
    const now = new Date();
    let expiresAt: Date;
    let subscriptionCode: string | null = null;
    let emailToken: string | null = null;
    let nextPaymentDate: Date | null = null;

    // Handle monthly subscription creation
    if (transaction.paymentPlan !== 'BASIC_ONETIME') {
      expiresAt = addMonths(now, 1);

      // Try to extract subscription details from verification response
      if (verification.data.subscription) {
        subscriptionCode = verification.data.subscription.subscription_code;
        emailToken = verification.data.subscription.email_token;
        nextPaymentDate = new Date(
          verification.data.subscription.next_payment_date
        );
        console.log(
          'Extracted from verification - subscription code:',
          subscriptionCode
        );
        console.log('Extracted from verification - email token:', emailToken);
        console.log(
          'Extracted from verification - next payment date:',
          nextPaymentDate
        );
      } else {
        console.warn(
          'No subscription data in verification response, fetching subscription...'
        );
        // Fallback: Fetch subscription using customer code and plan
        const customer = await getOrCreateCustomer(
          verification.data.customer.email,
          verification.data.customer.first_name || '',
          verification.data.customer.last_name || ''
        );
        const subscriptions = await paystack.subscription.list({
          customer: customer.customer_code,
          plan: PAYSTACK_PLAN_CODES[transaction.paymentPlan].NGN,
        });
        console.log('Fetched subscriptions for customer:', subscriptions);

        // Find all subscriptions for the plan and select the most recent active one
        const matchingSubscriptions = subscriptions.data.filter(
          (sub: any) =>
            sub.plan.plan_code ===
              PAYSTACK_PLAN_CODES[transaction.paymentPlan].NGN &&
            sub.status === 'active'
        );
        const activeSubscription = matchingSubscriptions.sort(
          (a: any, b: any) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        )[0]; // Sort by createdAt descending and take the first (most recent)

        if (activeSubscription) {
          subscriptionCode = activeSubscription.subscription_code;
          emailToken = activeSubscription.email_token;
          nextPaymentDate = new Date(activeSubscription.next_payment_date);
          console.log(
            'Fetched from subscription list - subscription code:',
            subscriptionCode
          );
          console.log(
            'Fetched from subscription list - email token:',
            emailToken
          );
          console.log(
            'Fetched from subscription list - next payment date:',
            nextPaymentDate
          );
        } else {
          console.error('No active subscription found for this plan');
        }
      }
    } else {
      expiresAt = new Date(now.getTime() + 15 * 60 * 1000); // 15 minutes for one-time
    }

    // Log the values before updating
    console.log('Updating user with:', {
      payment_plan: transaction.paymentPlan,
      payment_plan_expires_at: expiresAt,
      subscription_code: subscriptionCode,
      email_token: emailToken,
      default_authorization: authorization.authorization_code,
    });

    // Update user with payment details
    await updateUser(transaction.userId, {
      payment_plan: transaction.paymentPlan,
      payment_plan_expires_at: expiresAt,
      subscription_code: subscriptionCode,
      email_token: emailToken,
      default_authorization: authorization.authorization_code,
    });

    // Store card details, including subscription data for monthly plans
    if (transaction.paymentPlan !== 'BASIC_ONETIME') {
      // Disable all previous UserCard subscriptions for this user
      await db.userCard.updateMany({
        where: {
          userId: transaction.userId,
          subscription_status: 'ACTIVE',
        },
        data: {
          subscription_status: 'INACTIVE',
        },
      });

      // Create new UserCard with active subscription
      await db.userCard.create({
        data: {
          userId: transaction.userId,
          authorization_code: authorization.authorization_code,
          last4: authorization.last4 || '',
          exp_month: authorization.exp_month?.toString().padStart(2, '0') || '',
          exp_year: authorization.exp_year?.toString() || '',
          brand: authorization.brand || '',
          reusable: authorization.reusable || false,
          subscription_code: subscriptionCode,
          email_token: emailToken,
          next_payment_date: nextPaymentDate,
          subscription_status: 'ACTIVE', // Set as active
        },
      });
    } else {
      await db.userCard.create({
        data: {
          userId: transaction.userId,
          authorization_code: authorization.authorization_code,
          last4: authorization.last4 || '',
          exp_month: authorization.exp_month?.toString().padStart(2, '0') || '',
          exp_year: authorization.exp_year?.toString() || '',
          brand: authorization.brand || '',
          reusable: false,
        },
      });
    }

    return {
      ok: true,
      status: 200,
      message: 'Payment verified and user updated',
      data: { reference, status: 'success' },
    };
  } catch (error: any) {
    console.error('Error verifying subscription:', error);
    return {
      ok: false,
      status: 500,
      message: 'Failed to verify subscription',
      error: error.message,
    };
  }
};

export const cancelUserSubscription = async (userId: string) => {
  const user = await db.user.findUnique({ where: { id: userId } });
  if (!user?.subscription_code || !user.email_token) {
    return {
      ok: false,
      status: 400,
      message: 'User has no active subscription',
    };
  }

  const response = await paystack.subscription.disable({
    code: user.subscription_code,
    token: user.email_token,
  });

  if (response.status !== true) {
    return { ok: false, status: 400, message: 'Cancellation failed' };
  }

  await updateUser(userId, {
    payment_plan: null,
    payment_plan_expires_at: null,
    subscription_code: null,
    email_token: null,
  });

  return { ok: true, status: 200, message: 'Subscription cancelled' };
};

export const getUserCards = async (userId: string) => {
  const cards = await db.userCard.findMany({ where: { userId } });
  return { ok: true, status: 200, data: cards };
};

export const removeCard = async (
  userId: string,
  authorization_code: string
) => {
  await db.userCard.deleteMany({
    where: {
      userId,
      authorization_code,
    },
  });
  return { ok: true, status: 200, message: 'Card removed' };
};

// old code that works 90%
