-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "Adminrule1" TEXT,
ADD COLUMN     "Adminrule2" TEXT,
ADD COLUMN     "Adminrule3" TEXT,
ADD COLUMN     "Adminrule4" TEXT,
ADD COLUMN     "Adminrule5" TEXT,
ADD COLUMN     "ExamCountry1" TEXT,
ADD COLUMN     "ExamCountry10" TEXT,
ADD COLUMN     "ExamCountry2" TEXT,
ADD COLUMN     "ExamCountry3" TEXT,
ADD COLUMN     "ExamCountry4" TEXT,
ADD COLUMN     "ExamCountry5" TEXT,
ADD COLUMN     "ExamCountry6" TEXT,
ADD COLUMN     "ExamCountry7" TEXT,
ADD COLUMN     "ExamCountry8" TEXT,
ADD COLUMN     "ExamCountry9" TEXT,
ADD COLUMN     "ExamType1" TEXT,
ADD COLUMN     "ExamType10" TEXT,
ADD COLUMN     "ExamType10SubGrades" TEXT,
ADD COLUMN     "ExamType10Subjects" TEXT,
ADD COLUMN     "ExamType1SubGrades" TEXT,
ADD COLUMN     "ExamType1Subjects" TEXT,
ADD COLUMN     "ExamType2" TEXT,
ADD COLUMN     "ExamType2SubGrades" TEXT,
ADD COLUMN     "ExamType2Subjects" TEXT,
ADD COLUMN     "ExamType3" TEXT,
ADD COLUMN     "ExamType3SubGrades" TEXT,
ADD COLUMN     "ExamType3Subjects" TEXT,
ADD COLUMN     "ExamType4" TEXT,
ADD COLUMN     "ExamType4SubGrades" TEXT,
ADD COLUMN     "ExamType4Subjects" TEXT,
ADD COLUMN     "ExamType5" TEXT,
ADD COLUMN     "ExamType5SubGrades" TEXT,
ADD COLUMN     "ExamType5Subjects" TEXT,
ADD COLUMN     "ExamType6" TEXT,
ADD COLUMN     "ExamType6SubGrades" TEXT,
ADD COLUMN     "ExamType6Subjects" TEXT,
ADD COLUMN     "ExamType7" TEXT,
ADD COLUMN     "ExamType7SubGrades" TEXT,
ADD COLUMN     "ExamType7Subjects" TEXT,
ADD COLUMN     "ExamType8" TEXT,
ADD COLUMN     "ExamType8SubGrades" TEXT,
ADD COLUMN     "ExamType8Subjects" TEXT,
ADD COLUMN     "ExamType9" TEXT,
ADD COLUMN     "ExamType9SubGrades" TEXT,
ADD COLUMN     "ExamType9Subjects" TEXT,
ALTER COLUMN "id" SET DEFAULT substring(gen_random_uuid()::text, 1, 10),
ALTER COLUMN "loanInformation" DROP NOT NULL;

-- AlterTable
ALTER TABLE "School" ALTER COLUMN "id" SET DEFAULT substring(gen_random_uuid()::text, 1, 10);
